### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by pandureynaldo** [wizacha/AwsSignatureMiddleware#10]
i did the [README.md](https://github.com/wizacha/AwsSignatureMiddleware/blob/master/README.md) but always got error

```
{
    "name": "PHP Notice",
    "message": "Undefined index: host",
    "code": 8,
    "type": "yii\\base\\ErrorException",
    "file": "E:\\xampp\\htdocs\\logisly\\vendor\\wizacha\\aws-signature-middleware\\src\\Middleware\\AwsSignatureMiddleware.php",
    "line": 75,
    "stack-trace": [
        "#0 E:\\xampp\\htdocs\\logisly\\vendor\\wizacha\\aws-signature-middleware\\src\\Middleware\\AwsSignatureMiddleware.php(75): yii\\base\\ErrorHandler->handleError(8, 'Undefined index...', 'E:\\\\xampp\\\\htdocs...', 75, Array)",
        "#1 [internal function]: Wizacha\\Middleware\\AwsSignatureMiddleware->removePort('endpoint.eu-wes...')",
        "#2 E:\\xampp\\htdocs\\logisly\\vendor\\wizacha\\aws-signature-middleware\\src\\Middleware\\AwsSignatureMiddleware.php(53): array_map(Array, Array)",
        "#3 E:\\xampp\\htdocs\\logisly\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Connections\\Connection.php(257): Wizacha\\Middleware\\AwsSignatureMiddleware->Wizacha\\Middleware\\{closure}(Array)",
        "#4 E:\\xampp\\htdocs\\logisly\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Connections\\Connection.php(233): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array, Object(Elasticsearch\\Connections\\Connection), Object(Elasticsearch\\Transport), Array)",
        "#5 E:\\xampp\\htdocs\\logisly\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Transport.php(115): Elasticsearch\\Connections\\Connection->performRequest('POST', '/order_index/_s...', Array, '{\"query\":{\"mult...', Array, Object(Elasticsearch\\Transport))",
        "#6 E:\\xampp\\htdocs\\logisly\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Client.php(1591): Elasticsearch\\Transport->performRequest('POST', '/order_index/_s...', Array, Array, Array)",
        "#7 E:\\xampp\\htdocs\\logisly\\vendor\\elasticsearch\\elasticsearch\\src\\Elasticsearch\\Client.php(1216): Elasticsearch\\Client->performRequest(Object(Elasticsearch\\Endpoints\\Search))",
        "#8 E:\\xampp\\htdocs\\logisly\\api\\modules\\v2\\controllers\\OrderApiController.php(1087): Elasticsearch\\Client->search(Array)",
        "#9 [internal function]: api\\modules\\v2\\controllers\\OrderApiController->actionSearch()",
        "#10 E:\\xampp\\htdocs\\logisly\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)",
        "#11 E:\\xampp\\htdocs\\logisly\\vendor\\yiisoft\\yii2\\base\\Controller.php(180): yii\\base\\InlineAction->runWithParams(Array)",
        "#12 E:\\xampp\\htdocs\\logisly\\vendor\\yiisoft\\yii2\\base\\Module.php(528): yii\\base\\Controller->runAction('search', Array)",
        "#13 E:\\xampp\\htdocs\\logisly\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('v2/order-api/se...', Array)",
        "#14 E:\\xampp\\htdocs\\logisly\\vendor\\yiisoft\\yii2\\base\\Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
        "#15 E:\\xampp\\htdocs\\logisly\\api\\web\\index.php(17): yii\\base\\Application->run()",
        "#16 {main}"
    ]
}
```

can someone help?

**Comment by Guillaume-Rossignol** [comment]
Wizacha doesn't maintain this repository any more. You should check https://github.com/wizacha/AwsSignatureMiddleware/network/members for an active fork.
